<a href="https://colab.research.google.com/github/Musfirah-Ansari/pythonBasics/blob/main/pythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Machine Learning")

Machine Learning


In [3]:
x = 5
if x > 10:
  print("x is greater than 10")

In [6]:
name = "musfirah"

In [20]:
print(type(name))

<class 'str'>


In [8]:
age = 22

In [9]:
work = "Software developer"

In [10]:
workplace = "BankAlfalah"

In [17]:
salary = 999999.00

# f string

In [19]:
print(f"My name is {name}. I am {age} years old. I work as a {work} at {workplace}. I earn {salary} per month")


My name is musfirah. I am 22 years old. I work as a Software developer at BankAlfalah. I earn 99999.0 per month


# Types

In [21]:
print(type(age))

<class 'int'>


In [22]:
print(type(work))

<class 'str'>


In [23]:
print(type(workplace))

<class 'str'>


In [24]:
print(type(salary))

<class 'float'>


In [26]:
price = 35.67
year = 2024
is_admin = True

In [27]:
print(type(price))
print(type(year))
print(type(is_admin))

<class 'float'>
<class 'int'>
<class 'bool'>


In [28]:
year = float(year)

In [29]:
print(type(year))

<class 'float'>


# Taking User input

In [41]:
my_name = input("Please enter your name here. ")

Please enter your name here. MUSFI


In [42]:
print(my_name)

MUSFI


In [49]:
my_age = input("Please enter your age ")

Please enter your age 311


In [50]:
#Total = my_name + my_age
Total = my_name + str(my_age)

In [51]:
print(Total)

MUSFI311


# Area

In [87]:
length = 5
width = 6
area = length * width

print(f"The area is {area}")

The area is 30


# Shopping cart program

In [174]:
cart = {}

#price * quantity
cart["Apple"] = 1.5 * 3
cart["Banana"] = 0.75 * 5

totalsum = cart["Apple"] + cart["Banana"]

print(f"The total sum of apples in cart is ${cart['Apple']}")
print(f"The total sum of bananas in cart is ${cart['Banana']}")
print(f"Total sum of all the fruits is ${totalsum}")

The total sum of apples in cart is $4.5
The total sum of bananas in cart is $3.75
Total sum of all the fruits is $8.25


# Indexing

In [90]:
credit_card_number = "1234-5678-9012-3456"
print(credit_card_number[0])
print(credit_card_number[5:9])
print(credit_card_number[:4])
print(credit_card_number[1:9:2]) #step size
print(credit_card_number[1:-9])
print(credit_card_number[:-1])
print(credit_card_number[::-1])

1
5678
1234
2457
234-5678-
1234-5678-9012-345
6543-2109-8765-4321


In [91]:
CCN = input("Please enter your CCN: ")


Please enter your CCN: 1234-5678-9012-3456


# Printing Credit Cart numbers in encryted form using both positive and negative indexing

In [113]:
encrypted = CCN[15:19] #positive indexing
encrypted2 = CCN[-4:] #negative indexing
print(f"Your Credit Card is : ****-****-****-{encrypted}")
print(f"Your Credit Card is : ****-****-****-{encrypted2}")

Your Credit Card is : ****-****-****-3456
Your Credit Card is : ****-****-****-3456


In [120]:
CCN = input("Please enter your CCN: ")
encrypted = ""

for i in range(len(CCN)):
    if i < 15:
        if CCN[i] != '-':
            encrypted += '*'
        else:
            encrypted += '-'
    else:
        encrypted += CCN[i]

print(f"Your Debit Card is: {encrypted}")

Please enter your CCN: 1234-5678-9012-3456
Your Debit Card is: ****-****-****-3456


# String Methods


In [135]:
x = "my name is musfirah-fayyaz ansari. My age is 22."

In [136]:
x.find("s")

9

In [137]:
x.rfind("i")

42

In [138]:
x.capitalize()

'My name is musfirah-fayyaz ansari. my age is 22.'

In [139]:
x.title()

'My Name Is Musfirah-Fayyaz Ansari. My Age Is 22.'

In [140]:
x.upper()

'MY NAME IS MUSFIRAH-FAYYAZ ANSARI. MY AGE IS 22.'

In [141]:
x.lower()

'my name is musfirah-fayyaz ansari. my age is 22.'

In [142]:
x.isdigit()

False

In [143]:
x.isalpha()

False

In [144]:
x.count("-")

1

In [145]:
x.replace("-", "--")

'my name is musfirah--fayyaz ansari. My age is 22.'

In [146]:
x.split()

['my', 'name', 'is', 'musfirah-fayyaz', 'ansari.', 'My', 'age', 'is', '22.']

In [151]:
len(x)

48

In [158]:
email = "misbah.haque@xloopdigital.com"

path = "C:/Users/Misbah/Documents/file.txt"

In [159]:
parts = path.split("/")
print(parts)

['C:', 'Users', 'Misbah', 'Documents', 'file.txt']


In [160]:
last_str = email.rfind("@") #reverse find
print(last_str)
# last str will find the index of @
#we will use that index to slice out the domain
domain = email[last_str+1:]
print(domain)

12
xloopdigital.com


# Validate user input exercise

In [170]:
uname = input("Please enter your name: ")

if len(uname) > 12:
  print("Username is no more than 12 characters.") # uname is no mre than 12 char
elif not uname.find(" ")==-1:
  print("Username cannot contain spaces.") # uname must not contain spaces
#elif not uname.isdigit():
elif any(char.isdigit() for char in uname):
  print("Username cannot contain digits.") # uname must not contain digits
else:
  print("Username is valid.")

Please enter your name: musfi.rah
Username is valid.


# Format Specifiers

In [173]:
price1 = 2.44
price2 = -44
price3 = 354.5

print(f"price 1 is ${price1:.1f}")
print(f"price 1 is ${price:>10}")
print(f"price 1 is ${price:^10}")

price 1 is $2.4
price 1 is $     35.67
price 1 is $  35.67   


# Exercise

In [194]:
# Create a product price table displaying the price, tax (8%), and total price for three products, formatted with proper alignment and precision using f-strings.

prod1 = "Macbook"
price1 = 1300000.0
prod2 = "Iphone"
price2 = 4647000
tax_rate = 0.08
tax1 = price1*tax_rate
tax2 = price2*tax_rate

print("="*11 + "Product Price Table" + "="*11)

print(f"{'Product:':<15} {'Price:':>10} {'Tax (8%):' :>15}")
print(f"{prod1:<15} {price1:>10.2f} {tax1:>15.2f}")
print(f"{prod2:<15} {price2:>10.2f} {tax2:>15.2f}")

print("="*42)

===========Product Price Table===========
Product:            Price:       Tax (8%):
Macbook         1300000.00       104000.00
Iphone          4647000.00       371760.00


# Nested Loops

In [201]:
row = 8
col = 8
symbol = ' Musfirah '

for x in range(row):
  for y in range(col):
    print(symbol, end="")
  print()

 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 
 Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah  Musfirah 


# Match case

In [208]:
day = int(input("Please enter day number here: "))
match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case 4:
    print("Thursday")
  case 5:
    print("Friday")
  case 6:
    print("Saturday")
  case 7:
    print("Sunday")
  case _:
    print("Invalid day number")

Please enter day number here: 6
Saturday


# List Comprehensions

In [213]:
double = [x*2 for x in range(10) if x>2 ]
print(double)

[6, 8, 10, 12, 14, 16, 18]


In [212]:
type(double)

list

# Exercises

In [216]:
salaries = [50000, 60000, 70000]

new_salaries = [x*1.1 for x in salaries]

print(new_salaries)

[55000.00000000001, 66000.0, 77000.0]


# Functions & Advanced Python Concepts
(To perform repetitive tasks)

In [217]:
def sum(a, b):
  sum = a+b
  return sum

sum(4, 4)

8

In [219]:
def multiply(a, b):
  multiply = a*b
  return multiply

multiply(4, 4)

16

In [22]:
def divide(a, b):
  if b == 0:
    return "Cannot divide by zero"
  else:
    divide = a/b
    return divide

divide(16, 0)

'Cannot divide by zero'

In [2]:
def subtract(a, b):
  subtract = a-b
  return subtract

subtract(4, 3)

1

In [6]:
def happy_bday(name):

  print(f"Happy birthday to you, {name}")
  print(f"Happy birthday to you, {name}")
  print(f"Happy birthday dear {name}")
  print(f"Happy birthday to you, {name}")
  print()

happy_bday("Musfirah")

Happy birthday to you, Musfirah
Happy birthday to you, Musfirah
Happy birthday dear Musfirah
Happy birthday to you, Musfirah



# Concept of positional arguments

In [9]:
#Giving argument at wrong position getting wrong output

def happy_bday(name, age):

  print(f"Happy birthday to you, {name}")
  print(f"You are {age} years old")
  print()

happy_bday(22, "Musfirah")

Happy birthday to you, 22
You are Musfirah years old



In [15]:
#Giving correct arguments at correct positions

def happy_bday(name, age):

  print(f"Happy birthday to you, {name}")
  print(f"You are {age} years old")
  print()

happy_bday("Musfirah", 22)
happy_bday("Musfirah Fayyaz", 24)
happy_bday("Musfirah Fayyaz Ahmed", 26)
happy_bday("Musfirah Fayyaz Ahmed Ansari", 28)

Happy birthday to you, Musfirah
You are 22 years old

Happy birthday to you, Musfirah Fayyaz
You are 24 years old

Happy birthday to you, Musfirah Fayyaz Ahmed
You are 26 years old

Happy birthday to you, Musfirah Fayyaz Ahmed Ansari
You are 28 years old



In [13]:
#Again giving argument at wrong position getting wrong output
# Please take care of its order or position

def happy_bday(name, age, mood):

  print(f"Happy birthday to you, {name}")
  print(f"You are {age} years old")
  print(f"You are feeling {mood} today")

  print()

happy_bday("Excited","Musfirah", 22)

Happy birthday to you, Excited
You are Musfirah years old
You are feeling 22 today



# Invoice Functions

In [27]:
def inv_func(name, money):

  print(f"My name is, {name}")
  print(f"I earned {money: .2f} this month") #round off to 2
  print()

inv_func("Musfirah", 99999.0555)

My name is, Musfirah
I earned  99999.06 this month



# Default Arguments

In [24]:
def happy_bday(name, age=18):

  print(f"Happy birthday to you, {name}")
  print(f"You are {age} years old")
  print()

happy_bday("Musfirah")

Happy birthday to you, Musfirah
You are 18 years old



In [40]:
def create_name(first, last):
  first = first.capitalize()
  last = last.capitalize()
  return f"{first} {last}"

create_name("musfirah", "fayyaz")

'Musfirah Fayyaz'

In [39]:
def net_price(price, discount = 0, tax = 0.05):
  return price * (1 - discount) * (1 + tax)

print(net_price(500, 0.1, 0))
print(net_price(500, tax = 0.03))
net_price(500, 0.1, 0)
net_price(500, tax = 0.03)

450.0
515.0


515.0

# KEYWORD ARGUMENT



In [31]:
def hey(greet, title, first, last):

  print(f"{greet} {title} {first} {last}")

hey("Hey!", "Ms.", "MUSFIRAH", "FAYYAZ")
hey("Hey!", "Ms.", last = "FAYYAZ", first="MUSFIRAH")

Hey! Ms. MUSFIRAH FAYYAZ
Hey! Ms. MUSFIRAH FAYYAZ


In [42]:
def get_phone(country, area, first, last):

  print(f"+{country}-{area}-{first}-{last}")

get_phone(country=92, area= 333, last = 564, first=5443)

+92-333-5443-564


# Arbitray (args & kwargs)

In [11]:
#getting error while passing more unequal arguments as compare to the arguments defined in function
#before using args

def sum(a, b):
  return a+b

sum(4, 4, 4)

TypeError: sum() takes 2 positional arguments but 3 were given

In [21]:
def sum(*args):
  print(type(args))
  print()   #for gap
  total = 0
  for i in args:
    total += i
  return total

sum(11, 22, 33, 44, 55, 66, 77, 88, 99)

<class 'tuple'>



495

In [16]:
def display_name(*args):
  for i in args:
    print(i, end=" ")

display_name("Musfirah", "Fayyaz", "Ahmed", "Ansari")

Musfirah Fayyaz Ahmed Ansari 

In [22]:
def print_address(**kwargs):
  print(type(kwargs))
  print()   #for gap
  for key, value in kwargs.items():
    print(f"{key}: {value}")

print_address(street="123 Main St", city="Anytown", state="CA", zipcode="12345")

<class 'dict'>

street: 123 Main St
city: Anytown
state: CA
zipcode: 12345


# Exercise

In [50]:
def shipping_label(*args, **kwargs):
  for i in args:
    print(i, end=" ")
    print()
    print()
  for key, value in kwargs.items():
    print(f"{key}: {value}")
shipping_label("Musfirah", "Fayyaz", "Ahmed", "Ansari", street="123 Main St", city="Anytown", state="CA", zipcode="12345")


Musfirah 

Fayyaz 

Ahmed 

Ansari 

street: 123 Main St
city: Anytown
state: CA
zipcode: 12345


In [57]:
def shipping_label (*args, **kwargs):
  for i in args:
    print(i, end=" ")
  print()
  print()
  print(f"{kwargs.get('street')}")

  print(f"{kwargs.get('city')}, {kwargs.get('province')}, {kwargs.get('zip')}")

shipping_label("Ms.", "Musfirah", "Fayyaz",
street="Block 4 Clifton", city="Karachi", province="Sindh", zip="74500")

Ms. Musfirah Fayyaz 

Block 4 Clifton
Karachi, Sindh, 74500


In [59]:

def shipping_label(*args, **kwargs):
  for i in args:
    print(i, end=" ")
  print()
  print()
  print(f"{kwargs.get('street')}")
  print(f"{kwargs.get('city')}, {kwargs.get('province')}, {kwargs.get('zip')}")

shipping_label("Ms.", "Musfirah", "Fayyaz",
street="Clifton Block 4", city="Karachi", province="Sindh", zip="74500")

Ms. Musfirah Fayyaz 

Clifton Block 4
Karachi, Sindh, 74500


# Dictionary Assignment

In [224]:
# Create a simple bank system using a dictionary to store customer names & their balances. The program should allow users to enter a customer's name & display their balances. If the customer does not exist, inform the user that the customer is not found.

# EDA - NUMPY & PANDAS

# NumPy Numerical Python

NumPy (library) handles multi dimentional arrays easily. All maths computations are helpful.
Import in models in the form of dictionary.
Pandas is used to make this dictionary form datat into table.

In [60]:
import numpy as np  #you can use np and any other word for reference

In [62]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [63]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:", array_2d)

2D Array: [[1 2 3]
 [4 5 6]]


In [65]:

# Generate a 1D array of zeros with a specified size
zeros_array = np.zeros(5)  # Creates an array of 5 zeros
print(zeros_array)

# Generate a 2D array of zeros with specified rows and columns
zeros_2d_array = np.zeros((3, 4)) # Creates a 3x4 array of zeros
zeros_2d_array

[0. 0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
# Generate a 1D array of zeros with a specified size
zeros_array = np.ones(5)  # Creates an array of 5 zeros
print(zeros_array)

# Generate a 2D array of zeros with specified rows and columns
zeros_2d_array = np.ones((3, 4)) # Creates a 3x4 array of zeros
zeros_2d_array

[1. 1. 1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
range_array = np.arange(0, 10, 2) #starting index, ending index, step size
print("Array with range:", range_array)

Array with range: [0 2 4 6 8]


In [71]:
p_array = np.full((5,4), 5)
print(p_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [76]:
lin_array = np.linspace(10, 30, 3)  #start, end, number of values
print("Evenly spaced values:", lin_array)

Evenly spaced values: [10. 20. 30.]


In [77]:
arange_array = np.arange(10, 30, 5)
print(arange_array)

[10 15 20 25]


In [78]:
b = np.random.uniform(10, 30, 5)
print(b)

[10.79085714 25.39942112 26.57478528 21.03338801 16.4866974 ]


In [79]:
a = np.random.random((3, 4))
print(a)

[[0.61669327 0.19782928 0.74869057 0.3789249 ]
 [0.80927424 0.7586037  0.12294397 0.73088723]
 [0.75577937 0.1669054  0.84181955 0.30017475]]


In [85]:
c = np.random.randint(10, 30, (3,5))
print(c)

[[10 14 22 25 16]
 [11 27 21 14 10]
 [13 18 22 21 10]]


In [86]:
print(c.shape)

(3, 5)


In [87]:
print(c.ndim)

2


In [88]:
print(c.size)

15


In [89]:
print(c.dtype)

int64


In [91]:
d = a.reshape(2, 6)
print(d)
print(d.shape)

[[0.61669327 0.19782928 0.74869057 0.3789249  0.80927424 0.7586037 ]
 [0.12294397 0.73088723 0.75577937 0.1669054  0.84181955 0.30017475]]
(2, 6)


In [94]:

list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

numpy_array = np.array(list)

numpy_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
array_1 = np.array([1, 2, 3])
array_2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array_1, array_2))

concatenated_array

array([1, 2, 3, 4, 5, 6])

In [102]:

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

addition_result = np.add(a, b)  # or a + b
print("Addition:", addition_result)

subtraction_result = np.subtract(a, b) # or a - b
print("Subtraction:", subtraction_result)

multiplication_result = np.multiply(a, b) # or a * b
print("Multiplication:", multiplication_result)

division_result = np.divide(a, b) # or a / b
print("Division:", division_result)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [101]:
from time import process_time

py_list = (i for i in range(10000000))
start_time = process_time()
py_list = [i+5 for i in py_list]
end_time = process_time()
print(end_time - start_time)

1.4664984640000043


In [103]:
#TEMPERATTURE READING OF MONTH Assignment

#numpy arrays using random function (between 15 to 35)
#.min .max .average functions
#values greater than 30 should be inserted in new variable or new array
#tell location of last one using rmax
#change the dimension of datta set use 5 week instead 4, pad 2 extra values in temp dataset or make new var & remove any 2 val


In [ ]:

def create_account(accounts):
  name = input("Enter account holder's name: ")
  account_number = input("Enter account number: ")
  if account_number in accounts:
    print("Account number already exists.")
    return
  accounts[account_number] = {"name": name, "balance": 0, "transactions": []}
  print(f"Account created for {name} (Account #{account_number})")

def deposit(accounts):
  account_number = input("Enter account number: ")
  if account_number not in accounts:
    print("Account not found.")
    return
  amount = float(input("Enter amount to deposit: "))
  if amount <= 0:
    print("Invalid deposit amount.")
    return
  accounts[account_number]["balance"] += amount
  accounts[account_number]["transactions"].append(f"Deposit: +${amount:.2f}")
  print(f"${amount:.2f} deposited successfully.")

def withdraw(accounts):
  account_number = input("Enter account number: ")
  if account_number not in accounts:
    print("Account not found.")
    return
  amount = float(input("Enter amount to withdraw: "))
  if amount <= 0:
    print("Invalid withdrawal amount.")
    return
  if accounts[account_number]["balance"] < amount:
    print("Insufficient funds.")
    return
  accounts[account_number]["balance"] -= amount
  accounts[account_number]["transactions"].append(f"Withdrawal: -${amount:.2f}")
  print(f"${amount:.2f} withdrawn successfully.")

def check_balance(accounts):
  account_number = input("Enter account number: ")
  if account_number not in accounts:
    print("Account not found.")
    return
  balance = accounts[account_number]["balance"]
  print(f"Account balance: ${balance:.2f}")

def view_transactions(accounts):
  account_number = input("Enter account number: ")
  if account_number not in accounts:
    print("Account not found.")
    return
  transactions = accounts[account_number]["transactions"]
  if not transactions:
    print("No transactions found for this account.")
  else:
    print("Transaction history:")
    for transaction in transactions:
      print(transaction)

def main():
  accounts = {}  # Use a dictionary to store account information

  while True:
    print("\nBanking System Menu:")
    print("1. Create Account")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Check Balance")
    print("5. View Transactions")
    print("6. Exit")

    choice = input("Enter your choice: ")

    if choice == '1':
      create_account(accounts)
    elif choice == '2':
      deposit(accounts)
    elif choice == '3':
      withdraw(accounts)
    elif choice == '4':
      check_balance(accounts)
    elif choice == '5':
      view_transactions(accounts)
    elif choice == '6':
      print("Exiting...")
      break
    else:
      print("Invalid choice. Please try again.")

if __name__ == "__main__":
  main()

In [ ]:
#Practical application & mini project (banking system)
#write pass below each function so that it won't pass errors

#1 create acc

def create_acc(acc):
  name = input("Enter your name: ")
  acc_no = input("Enter account number: ")
  if acc_no in acc:
    print("Account number already exists.")
    return
  acc[acc_no] = {"name": name, "balance": 0, "transactions": []}
  print(f"Account created for {name}, (Account #{acc_no})")

#2 deposit
def deposit(amount):
  pass
  if amount <= 0:
    print("Invalid deposit amount.")

#3 withdraw

def withdraw(amount):
  pass
  if amount <= 0:
    print("Invalid withdrawal amount.")
#4 balance check
def check_balance(acc):
  pass
#5 view balance
def view_transactions(acc):
  pass
#6 end (optional)
def end():
  pass

def main():
  acc = {}  # Use a dictionary to store account information

  while True:
    print("Banking System Menu:")
    print("1. Create Account")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Check Balance")
    print("5. View Transactions")
    print("6. Exit")

    select = input("Enter number you want to choose: ")

    if select == '1':
      create_acc(acc)
    elif select == '2':
      deposit(acc)
    elif select == '3':
      withdraw(acc)
    elif select == '4':
      check_balance(acc)
    elif select == '5':
      view_transactions(acc)
    elif select == '6':
      print("Closing the MENU. Have a good day! Thankyou for reaching out")
      break
    else:
      print("Invalid number selected. Please try again.")

if __name__ == "__main__":
  main()

Banking System Menu:
1. Create Account
2. Deposit
3. Withdraw
4. Check Balance
5. View Transactions
6. Exit
